name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50
        args: --disable-all --enable=govet --enable=unused --enable=structcheck --enable=deadcode

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -failfast -timeout 60s -v ./...
